Top2000/Controllers/RankingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top2000.EF;

namespace Top2000.Controllers
{
    public class RankingsController : Controller
    {
        private Top2000Entities db = new Top2000Entities();

        // GET: Rankings
        public ActionResult Index(int? jaar)
        {
			ViewBag.Years = db.spYears().ToList();
            ViewBag.artist = db.spAllArtist().ToList();
            if (jaar == null)
			{
				var data = db.spSongList(2018);
				ViewBag.Year = 2018;
				return View(data.ToList());
			} else
			{
				var data = db.spSongList(jaar);
				ViewBag.Year = jaar;
				return View(data.ToList());
			}
        }
        //function5
        //overzicht van de noteringen van elk jaar
        public ActionResult ArtistYear(string artist)
        {
            var data = db.spArtistRanking(artist);
            return View(data.ToList());
        }
        //function4
        //overzicht van de song waarop geselecterd
        public ActionResult YearRanking(string songName, int? jaar)
        {
			if (jaar == null)
			{
				var data = db.spYearRanking(songName, 2018);
				return View(data.ToList());
			} else
			{
				var data = db.spYearRanking(songName, jaar);
				return View(data.ToList());
			}
		}

		public ActionResult SearchCase(string searchBy, string value, int? jaar)
		{
			if (searchBy == "artistname")
			{
				return RedirectToAction("ArtistGemiddelde", new { @artistname = value});
			}
			else if(searchBy == "songname")
			{
				return RedirectToAction("YearRanking", new { @songName = value, @jaar = jaar});
			}
			else
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
		}

        //function3
        // overzicht van de gemiddelde positie van een artiest en zijn liedjes
        public ActionResult ArtistGemiddelde(string artistname)
        {
			var data = db.spArtistGemiddelde(artistname);
			return View(data.ToList());
		}



        // GET: Rankings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRanking tblRanking = db.tblRanking.Find(id);
            if (tblRanking == null)
            {
                return HttpNotFound();
            }
            return View(tblRanking);
        }

        // GET: Rankings/Create
        public ActionResult Create()
        {
            ViewBag.SongID = new SelectList(db.tblSongs, "SongID", "SongName");
            return View();
        }

        // POST: Rankings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RankingID,SongID,RankingPosition,RankingYear")] tblRanking tblRanking)
        {
            if (ModelState.IsValid)
            {
                db.tblRanking.Add(tblRanking);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SongID = new SelectList(db.tblSongs, "SongID", "SongName", tblRanking.SongID);
            return View(tblRanking);
        }

        // GET: Rankings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRanking tblRanking = db.tblRanking.Find(id);
            if (tblRanking == null)
            {
                return HttpNotFound();
            }
            ViewBag.SongID = new SelectList(db.tblSongs, "SongID", "SongName", tblRanking.SongID);
            return View(tblRanking);
        }

        // POST: Rankings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RankingID,SongID,RankingPosition,RankingYear")] tblRanking tblRanking)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblRanking).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SongID = new SelectList(db.tblSongs, "SongID", "SongName", tblRanking.SongID);
            return View(tblRanking);
        }

        // GET: Rankings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRanking tblRanking = db.tblRanking.Find(id);
            if (tblRanking == null)
            {
                return HttpNotFound();
            }
            return View(tblRanking);
        }

        // POST: Rankings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblRanking tblRanking = db.tblRanking.Find(id);
            db.tblRanking.Remove(tblRanking);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Top2000/Views/Rankings/ArtistAverage.cshtml
@model IEnumerable<Top2000.EF.spArtistGemiddelde_Result>

@{
    ViewBag.Title = "ArtistAverage";
}

<h2>ArtistAverage</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (Html.BeginForm("ArtistAverage", "Rankings", FormMethod.Get))
    {
        <b style="color:white; float:right">
            Search:
            @Html.TextBox("artistname")<input id="artistname" type="submit" value="Search" />
        </b>
    }
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ArtistName)
        </th>
        <th>
            Gemiddelde
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ArtistName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Average_Position)
            </td>
        </tr>
    }

</table>

Top2000/Views/Rankings/ArtistGemiddelde.cshtml
@model IEnumerable<Top2000.EF.spArtistGemiddelde_Result>

@{
	ViewBag.Title = "ArtistGemiddelde";
}

<h2 class="text-white">ArtistYear</h2>


<table class="table table-light table-striped">
	<thead class="thead-light">
		<tr>
			<th>
				Gemiddelde
			</th>
			<th>
				Artiest
			</th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Average_Position)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.ArtistName)
			</td>
		</tr>
	}

</table>

Top2000/Views/Rankings/ArtistYear.cshtml
@model IEnumerable<Top2000.EF.spArtistRanking_Result>

@{
	ViewBag.Title = "ArtistYear";
}

<h2 class="text-white">ArtistYear</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>
<table class="table table-light table-striped">
	<thead class="thead-light">
		<tr>
			<th>
				Nr.
			</th>
			<th>
				Liedje
			</th>
			<th>
				Artiest
			</th>
			<th>
				Jaar
			</th>
		</tr>
	</thead>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.RankingPosition)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.SongName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.ArtistName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.RankingYear)
			</td>
		</tr>
	}

</table>

Top2000/Views/Rankings/Create.cshtml
@model Top2000.EF.tblRanking

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblRanking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SongID, "SongID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SongID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SongID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RankingPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RankingPosition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RankingPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RankingYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RankingYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RankingYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Top2000/Views/Rankings/Delete.cshtml
@model Top2000.EF.tblRanking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblRanking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RankingPosition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RankingPosition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RankingYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RankingYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSongs.SongName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSongs.SongName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Top2000/Views/Rankings/Details.cshtml
@model Top2000.EF.tblRanking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblRanking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RankingPosition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RankingPosition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RankingYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RankingYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblSongs.SongName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSongs.SongName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RankingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Top2000/Views/Rankings/Edit.cshtml
@model Top2000.EF.tblRanking

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblRanking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RankingID)

        <div class="form-group">
            @Html.LabelFor(model => model.SongID, "SongID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SongID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SongID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RankingPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RankingPosition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RankingPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RankingYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RankingYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RankingYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Top2000/Views/Rankings/Index.cshtml
@model IEnumerable<Top2000.EF.spSongList_Result>

@{
    ViewBag.Title = "Index";
}

<div class="bg-dark d-flex" style="width:100%">
	<div class="mr-auto">
		<h5 class="text-white">Lijst @ViewBag.Year</h5>
	</div>
	<div class="mr-auto">
		@using (Html.BeginForm())
		{
			@Html.DropDownList("jaar", new SelectList(ViewBag.Years, "jaar"), new { onchange = "this.form.submit();" })
		}
		@using (Html.BeginForm("ArtistYear", "Rankings"))
		{
			@Html.DropDownList("artist", new SelectList(ViewBag.artist, "artist"), new { onchange = "this.form.submit();" })
		}
	</div>
	<div class="ml-auto">
		@using (Html.BeginForm("SearchCase", "Rankings", FormMethod.Get))
		{
			<b style="color:white; float:right">
				<b>Search by: </b>
				<input type="hidden" name="jaar" value="@ViewBag.Year"/>
				@Html.RadioButton("searchBy", "songname", true)<text>songName</text>
				@Html.RadioButton("searchBy", "artistname")<text>artistname</text><br />
				Search:
				@Html.TextBox("value")<input type="submit" value="Search" />
			</b>
		}
	</div>
</div>
	<table class="table table-light table-striped">
		<thead class="thead-light">
			<tr>
				<th>
					NR.
				</th>
				<th>
					VERLOOP
				</th>
				<th>
					TITEL
				</th>
				<th>
					ARTIEST
				</th>
				<th>
					JAAR
				</th>
			</tr>
		</thead>
		<tbody>

			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.RankingPosition)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Verloop)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.SongName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.ArtistName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.SongYear)
					</td>
				</tr>
			}
		</tbody>
	</table>

Top2000/Views/Rankings/YearRanking.cshtml
@model IEnumerable<Top2000.EF.spYearRanking_Result>

@{
	ViewBag.Title = "YearRanking";
}

<h2 class="text-white">YearRanking</h2>

@if (!Model.Any())
{
	<div class="alert alert-primary" role="alert">
		<strong>Geen song met deze naam gevonden!</strong>
	</div>
}
else
{
		<table class="table table-light table-striped">
			<thead class="thead-light">
				<tr>
					<th>
						Nr.
					</th>
					<th>
						Liedjes
					</th>
					<th>
						Jaar van het liedje
					</th>
				</tr>
			</thead>
			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.RankingPosition)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.SongName)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.SongYear)
					</td>
				</tr>
			}

		</table>}